### PR TITLE
Complete data collection for camera calibration.

### PR DESCRIPTION
**Pull request by Xngzdai**
This edition is made offline. Tests are required on the machine. You should be able to collect all the data for the camera calibration by running the script `data_collector.py`. Let me know if any bug jumps out.

### CODE REVIEW

**Comment by kwesiRutledge** [comment]
I think I'll accept this without checking many of the files.

We should get a subset of these files to put into [kinova-arm](https://github.com/ozay-group/kinova-arm) soon.

**Comment by kwesiRutledge** [comment]
Hm. For some reason this seems to be stuck in step 2 when I try to run this on the robot. I'll try to diagnose where it is stuck.

**Comment by Xngzdai** [comment]
It would be helpful if you can share the return message. I can help with debugging!

The `data_collector.py` will call `kinova_image.py` in step 2. But you can directly execute `kinova_image.py` on its own. It will do three things: 1) connect to the kinova vision module, 2) capture a color and depth image, 3) save them. 

The possible error that I can think of may be: 1) `kinova_image.py` cannot fetch the stream (disconnection to the kinova gen3), 2) the format (size) between the color and depth image doesn't match, 3) the image being 'saved' is blank. Otherwise, I'm supposed to re-write the capture program.

**Comment by kwesiRutledge** [comment]
Sorry; I had to get something ready for a brief meeting with Necmiye and got delayed on this. 

Unfortunately, I can't seem to see where the Python program is stuck. Pressing CTRL+C doesn't work for some reason, so I can't see what function is the issue.

These are the messages on the screen:
```
Step 1: Generate the point cloud model from the static camera...
Saving to ply...
Done
Step 2: Capture one color image and one depth image by kinova camera...
[ WARN:0] global /root/OpenCV/modules/videoio/src/cap_gstreamer.cpp (898) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /root/OpenCV/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
1
^C
```

The robot is on, and it is able to show me an image via an OpenCV window. Unfortunately, after showing me the correct image in a plot, it does not continue to the next step.

**Comment by Xngzdai** [comment]
Thanks for sharing! I'm looking into it.

**Pull request merged**
